[build]
  command = ng build --prod
  publish = /opt/build/repo/hbdMAson/WebContents
  commandOrigin = config
  publishOrigin = config
[[redirects]]
  from = /*
  to = /index.html
  status = 200
  redirectsOrigin = config
